language: node_js

cache: yarn

notifications:
  email: false

node_js:
- 10
- 9
- 8

install:
- yarn

before_script:
- yarn ci

script:
- yarn build

after_success:
- if [[ $TRAVIS_NODE_VERSION == "8" ]]; then yarn codecov; fi

branches:
  except:
  - "/^v\\d+\\.\\d+\\.\\d+$/"

deploy:
  provider: npm
  email: uma.karimov@gmail.com
  api_key:
    secure: cqRv/8t1FueHih8uECWuBeMoR25RxZThNdJxWfmUiHsXIsYdW863+kX+dt7rK59XdklPNN2TkVQuUWMcE5uPnaUSi9dtB96nJ70AKJa1WMiw1Lw1ecyOGjHtVoXNrmDMLu6Tlsr5XAL7pkEwWnzphD1EAT5M/OSvBgBAGQM598nWyW27A3RzEj22DZrEXPqj7BzAr6ut4AAFkMqeFxDaKoOCh1HTwfDvgGTC9cuj+VXipJTQfW9mtZUnfwnR0rm/Y72F+C+zXxM0iQpv0SlfWU3KF3GL+G/cm94U9pVBfTYWKGYVaCN+i5HPdQUniPTlmdtLDqn4OT/Fn/dzmyEmV5b6nfqUPTSo9aFyDVEED0F9SHcw4vOx+3vQOX1Nu5DVRWTbBLiCgXwRpAOn/I4MBFb4zTQSwuhkFiYaGrKaQSOJUvNitZ3GEphNzQdDJU6TZepUEFu7tOwOF6/hh999C3pSNJLulyUuZjL60/gZZtZI/RfRBi2Hhc9HwVMuG12jrg7C/AjjW0cwF9sEMy0Ewf8Zm1gG2+Iu6+YXdftZUwqz1m7Ryl6SsAnhPwNyZqe+jDFX38DZ0218mMBWfav2WZfdiUVQa3LkuhXuxxMvJATYK/vGpDzFwGZ1QUfvlOsi7739Y2L1x4CSAgF+VJXvS0iJ9F2j3IAXjz5tVmK5tno=
  on:
    tags: true
    branch: master
    repo: dcodeteam/redux-utils
    condition: $TRAVIS_NODE_VERSION = 8
